# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7c39d460279852cf3afa2a022281ec12d752ce2331d5461cc4d2b4490addc0c1cade311b9bd713f537a6944b93a1ae8d241def6ef86c1a5cf8e2e2b6f94f822

test:
  secret_key_base: b799124520d43c9b6ec2eb40745bd58f8881cfe8b8373fb215436c90dc6cdafa76a742bf3e3c95b01ceb318a12baf58b64b893b2c8d55c8a72398c08c6c82e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
